apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: resource-group
  description: Módulo no-code para criação de "resource-group"
spec:
  type: terraform-module
  name: resource-group
  owner: squad-automacao
  lifecycle: production
  definition:
    input:
      - azurerm_key_vault_access_policy_object_id
      - azurerm_key_vault_name
      - azurerm_resource_group_location
      - azurerm_resource_group_name
      - tags
    output:
      - resource_group_location
      - resource_group_name
    dependsOn:
      - resource: terraform-azurerm-srv-key-vault
      - resource: terraform-azurerm-tdr-key-vault-access-policy
